package com.example.dao.mapper;

import com.example.dao.models.Score;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("sId") String sId, @Param("cId") String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated
     */
    int insert(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated
     */
    Score selectByPrimaryKey(@Param("sId") String sId, @Param("cId") String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated
     */
    List<Score> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Score record);
}